// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

#[allow(unused)]
use crate::{
    Appearance, PlayerColor, PlayerColors, StatusColorsRefinement, ThemeColorsRefinement,
    UserFontStyle, UserFontWeight, UserHighlightStyle, UserSyntaxTheme, UserTheme, UserThemeFamily,
    UserThemeStylesRefinement,
};

pub fn dank_neon() -> UserThemeFamily {
    UserThemeFamily {
        name: "Dank Neon".into(),
        author: "DankNeon".into(),
        themes: vec![UserTheme {
            name: "Dank Neon".into(),
            appearance: Appearance::Dark,
            styles: UserThemeStylesRefinement {
                colors: ThemeColorsRefinement {
                    border: Some(rgba(0x191b2aff).into()),
                    border_variant: Some(rgba(0x191b2aff).into()),
                    border_focused: Some(rgba(0x7496ccff).into()),
                    border_selected: Some(rgba(0x191b2aff).into()),
                    border_transparent: Some(rgba(0x191b2aff).into()),
                    border_disabled: Some(rgba(0x191b2aff).into()),
                    elevated_surface_background: Some(rgba(0x1d1f30ff).into()),
                    surface_background: Some(rgba(0x191b2aff).into()),
                    background: Some(rgba(0x191b2aff).into()),
                    element_background: Some(rgba(0x39ffbaff).into()),
                    element_hover: Some(rgba(0x2a2d4699).into()),
                    element_selected: Some(rgba(0x2a2d46ff).into()),
                    ghost_element_hover: Some(rgba(0x2a2d4699).into()),
                    ghost_element_selected: Some(rgba(0x2a2d46ff).into()),
                    text: Some(rgba(0xeff0f6ff).into()),
                    text_muted: Some(rgba(0xa5abcaff).into()),
                    status_bar_background: Some(rgba(0x191b2aff).into()),
                    title_bar_background: Some(rgba(0x1d1f30ff).into()),
                    toolbar_background: Some(rgba(0x191b2aff).into()),
                    tab_bar_background: Some(rgba(0x2a2d46ff).into()),
                    tab_inactive_background: Some(rgba(0x191b2aff).into()),
                    tab_active_background: Some(rgba(0x191b2aff).into()),
                    scrollbar_thumb_background: Some(rgba(0x656fa433).into()),
                    scrollbar_thumb_hover_background: Some(rgba(0x656fa444).into()),
                    scrollbar_thumb_border: Some(rgba(0x656fa433).into()),
                    scrollbar_track_background: Some(rgba(0x191b2aff).into()),
                    scrollbar_track_border: Some(rgba(0x191b2aff).into()),
                    editor_foreground: Some(rgba(0xeff0f6ff).into()),
                    editor_background: Some(rgba(0x191b2aff).into()),
                    editor_gutter_background: Some(rgba(0x191b2aff).into()),
                    editor_line_number: Some(rgba(0x858db7ff).into()),
                    editor_active_line_number: Some(rgba(0xeff0f6ff).into()),
                    editor_wrap_guide: Some(rgba(0x191b2aff).into()),
                    editor_active_wrap_guide: Some(rgba(0x191b2aff).into()),
                    link_text_hover: Some(rgba(0x01a8adff).into()),
                    ..Default::default()
                },
                status: StatusColorsRefinement {
                    conflict: Some(rgba(0xffee7aff).into()),
                    created: Some(rgba(0x39ffbaff).into()),
                    deleted: Some(rgba(0xff476eff).into()),
                    error: Some(rgba(0xff476eff).into()),
                    hidden: Some(rgba(0xa5abcaff).into()),
                    hint: Some(rgba(0x969696ff).into()),
                    ignored: Some(rgba(0xa5abcaff).into()),
                    modified: Some(rgba(0x94bfffff).into()),
                    ..Default::default()
                },
                player: None,
                syntax: Some(UserSyntaxTheme {
                    highlights: vec![
                        (
                            "attribute".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x39ffbaff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "boolean".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "comment".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x858db7ff).into()),
                                font_style: Some(UserFontStyle::Italic),
                                ..Default::default()
                            },
                        ),
                        (
                            "comment.doc".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x858db7ff).into()),
                                font_style: Some(UserFontStyle::Italic),
                                ..Default::default()
                            },
                        ),
                        (
                            "constant".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "constructor".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff476eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "emphasis".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xffca7aff).into()),
                                font_style: Some(UserFontStyle::Italic),
                                ..Default::default()
                            },
                        ),
                        (
                            "emphasis.strong".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff476eff).into()),
                                font_weight: Some(UserFontWeight(700.0)),
                                ..Default::default()
                            },
                        ),
                        (
                            "function".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff476eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "keyword".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff476eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "link_text".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x01f7f7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "link_uri".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x01f7f7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "number".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.bracket".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.delimiter".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.list_marker".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x94bfffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.escape".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.regex".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x94bfffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x94bfffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.special.symbol".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x94bfffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "tag".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff476eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "text.literal".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x94bfffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "type".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x39ffbaff).into()),
                                font_style: Some(UserFontStyle::Italic),
                                ..Default::default()
                            },
                        ),
                        (
                            "variable".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x39ffbaff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "variable.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf1b3f1ff).into()),
                                ..Default::default()
                            },
                        ),
                    ],
                }),
            },
        }],
    }
}
