// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

mod andromeda;
mod atelier;
mod ayu;
mod dank_neon;
mod git_hub_dark;
mod gruvbox;
mod one;
mod rose_pine;
mod sandcastle;
mod solarized;
mod summercamp;
mod tokyo_night;

pub use andromeda::*;
pub use atelier::*;
pub use ayu::*;
pub use dank_neon::*;
pub use git_hub_dark::*;
pub use gruvbox::*;
pub use one::*;
pub use rose_pine::*;
pub use sandcastle::*;
pub use solarized::*;
pub use summercamp::*;
pub use tokyo_night::*;

use crate::UserThemeFamily;

pub(crate) fn all_user_themes() -> Vec<UserThemeFamily> {
    vec![
        andromeda(),
        atelier(),
        ayu(),
        gruvbox(),
        one(),
        rose_pine(),
        sandcastle(),
        solarized(),
        summercamp(),
        git_hub_dark(),
        dank_neon(),
        tokyo_night(),
    ]
}
