// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

#[allow(unused)]
use crate::{
    Appearance, PlayerColor, PlayerColors, StatusColorsRefinement, ThemeColorsRefinement,
    UserFontStyle, UserFontWeight, UserHighlightStyle, UserSyntaxTheme, UserTheme, UserThemeFamily,
    UserThemeStylesRefinement,
};

pub fn rose_pine() -> UserThemeFamily {
    UserThemeFamily {
        name: "Rosé Pine".into(),
        author: "Zed Industries".into(),
        themes: vec![],
    }
}
