// This file was generated by the `theme_importer`.
// Be careful when modifying it by hand.

use gpui::rgba;

#[allow(unused)]
use crate::{
    Appearance, PlayerColor, PlayerColors, StatusColorsRefinement, ThemeColorsRefinement,
    UserFontStyle, UserFontWeight, UserHighlightStyle, UserSyntaxTheme, UserTheme, UserThemeFamily,
    UserThemeStylesRefinement,
};

pub fn tokyo_night() -> UserThemeFamily {
    UserThemeFamily {
        name: "Tokyo Night".into(),
        author: "Enkia".into(),
        themes: vec![UserTheme {
            name: "Tokyo Night".into(),
            appearance: Appearance::Dark,
            styles: UserThemeStylesRefinement {
                colors: ThemeColorsRefinement {
                    border: Some(rgba(0x101014ff).into()),
                    border_variant: Some(rgba(0x101014ff).into()),
                    border_focused: Some(rgba(0x545c7e33).into()),
                    border_selected: Some(rgba(0x101014ff).into()),
                    border_transparent: Some(rgba(0x101014ff).into()),
                    border_disabled: Some(rgba(0x101014ff).into()),
                    elevated_surface_background: Some(rgba(0x14141bff).into()),
                    surface_background: Some(rgba(0x16161eff).into()),
                    background: Some(rgba(0x1a1b26ff).into()),
                    element_background: Some(rgba(0x3d59a1dd).into()),
                    element_hover: Some(rgba(0x13131aff).into()),
                    element_selected: Some(rgba(0x202330ff).into()),
                    drop_target_background: Some(rgba(0x1e202eff).into()),
                    ghost_element_hover: Some(rgba(0x13131aff).into()),
                    ghost_element_selected: Some(rgba(0x202330ff).into()),
                    text: Some(rgba(0x787c99ff).into()),
                    text_muted: Some(rgba(0x787c99ff).into()),
                    status_bar_background: Some(rgba(0x16161eff).into()),
                    title_bar_background: Some(rgba(0x16161eff).into()),
                    toolbar_background: Some(rgba(0x16161eff).into()),
                    tab_bar_background: Some(rgba(0x16161eff).into()),
                    tab_inactive_background: Some(rgba(0x16161eff).into()),
                    tab_active_background: Some(rgba(0x16161eff).into()),
                    scrollbar_thumb_background: Some(rgba(0x868bc415).into()),
                    scrollbar_thumb_hover_background: Some(rgba(0x868bc410).into()),
                    scrollbar_thumb_border: Some(rgba(0x868bc415).into()),
                    scrollbar_track_background: Some(rgba(0x1a1b26ff).into()),
                    scrollbar_track_border: Some(rgba(0x101014ff).into()),
                    editor_foreground: Some(rgba(0xa9b1d6ff).into()),
                    editor_background: Some(rgba(0x1a1b26ff).into()),
                    editor_gutter_background: Some(rgba(0x1a1b26ff).into()),
                    editor_line_number: Some(rgba(0x363b54ff).into()),
                    editor_active_line_number: Some(rgba(0xa9b1d6ff).into()),
                    editor_wrap_guide: Some(rgba(0x101014ff).into()),
                    editor_active_wrap_guide: Some(rgba(0x101014ff).into()),
                    terminal_background: Some(rgba(0x16161eff).into()),
                    terminal_ansi_black: Some(rgba(0x363b54ff).into()),
                    terminal_ansi_bright_black: Some(rgba(0x363b54ff).into()),
                    terminal_ansi_red: Some(rgba(0xf7768eff).into()),
                    terminal_ansi_bright_red: Some(rgba(0xf7768eff).into()),
                    terminal_ansi_green: Some(rgba(0x73dacaff).into()),
                    terminal_ansi_bright_green: Some(rgba(0x41a6b5ff).into()),
                    terminal_ansi_yellow: Some(rgba(0xe0af68ff).into()),
                    terminal_ansi_bright_yellow: Some(rgba(0xe0af68ff).into()),
                    terminal_ansi_blue: Some(rgba(0x7aa2f7ff).into()),
                    terminal_ansi_bright_blue: Some(rgba(0x7aa2f7ff).into()),
                    terminal_ansi_magenta: Some(rgba(0xbb9af7ff).into()),
                    terminal_ansi_bright_magenta: Some(rgba(0xbb9af7ff).into()),
                    terminal_ansi_cyan: Some(rgba(0x7dcfffff).into()),
                    terminal_ansi_bright_cyan: Some(rgba(0x7dcfffff).into()),
                    terminal_ansi_white: Some(rgba(0x787c99ff).into()),
                    terminal_ansi_bright_white: Some(rgba(0xacb0d0ff).into()),
                    link_text_hover: Some(rgba(0x7dcfffff).into()),
                    ..Default::default()
                },
                status: StatusColorsRefinement {
                    conflict: Some(rgba(0xe0af68cc).into()),
                    created: Some(rgba(0x164846ff).into()),
                    deleted: Some(rgba(0x823c41ff).into()),
                    error: Some(rgba(0x515670ff).into()),
                    hidden: Some(rgba(0x787c99ff).into()),
                    hint: Some(rgba(0x969696ff).into()),
                    ignored: Some(rgba(0x515670ff).into()),
                    modified: Some(rgba(0x394b70ff).into()),
                    warning: Some(rgba(0xc49a5aff).into()),
                    ..Default::default()
                },
                player: None,
                syntax: Some(UserSyntaxTheme {
                    highlights: vec![
                        (
                            "attribute".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xbb9af7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "boolean".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff9e64ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "comment".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x51597dff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "comment.doc".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x51597dff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "constant".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff9e64ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "constructor".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf7768eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "emphasis".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xc0caf5ff).into()),
                                font_style: Some(UserFontStyle::Italic),
                                ..Default::default()
                            },
                        ),
                        (
                            "emphasis.strong".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xc0caf5ff).into()),
                                font_weight: Some(UserFontWeight(700.0)),
                                ..Default::default()
                            },
                        ),
                        (
                            "function".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x7aa2f7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "keyword".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xbb9af7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "label".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xc0caf5ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "link_text".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x73dacaff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "link_uri".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x73dacaff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "number".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xff9e64ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "operator".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "preproc".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x73dacaff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.bracket".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.delimiter".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.list_marker".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "punctuation.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x89ddffff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x9ece6aff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.escape".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xbb9af7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.regex".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x9ece6aff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x9ece6aff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "string.special.symbol".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x9ece6aff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "tag".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf7768eff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "text.literal".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x9ece6aff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "title".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xc0caf5ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "type".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0x0db9d7ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "variable".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xc0caf5ff).into()),
                                ..Default::default()
                            },
                        ),
                        (
                            "variable.special".into(),
                            UserHighlightStyle {
                                color: Some(rgba(0xf7768eff).into()),
                                ..Default::default()
                            },
                        ),
                    ],
                }),
            },
        }],
    }
}
